Mappings: 
  AmiRegionMap: 
    us-east-1: 
      "AMI": "ami-079db87dc4c10ac91"
    us-east-2: 
      "AMI": "ami-0ee4f2271a4df2d7d"
    us-west-1: 
      "AMI": "ami-0082110c417e4726e"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap 
      - AmiRegionMap
      - !Ref AWS::Region
      - AMI
      Tags:
        - Key: Name
          Value: !Join
            - ' '
            - - 'My Instance'
              - !Ref AWS::Region
      SecurityGroups:
      - !Ref MySecurityGroup
  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH,HTTP and HTTPS from anywhere
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0 # If you want to allow traffic for a specific IP address, you can use CidrIp: x.x.x.x/32
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0