Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-079db87dc4c10ac91
      Tags:
        - Key: Name
          Value: !Join
            - ' '
            - - 'My Instance'
              - !Ref AWS::Region